### ISSUE TITLE
How use For New Version React 16.9.0 And ReactNative ( Hook )

### ISSUE THREAD

**Issue by AMINDRH91** [uxitten/react-beep#3]
hello 
I used this library, of course, in a small project, I don't know what works in a large project, but it reduced the code a lot.

One problem I'm having about the new version of `React 16.9.0 And ReactNative 0.60 ` that I used `Hook`  
how to handel  this   `extends Beep(['Time'], React.Component)`  ??
tnx

**Comment by uxitten** [comment]
Hi @AMINDRH91 
Currently, react-beep doesn't support react hooks, maybe in the future possible.

But, now you can use a trick for this issue

```javascript
// A is hook function
function A({time}){
 ...
}

export default class extends Beep(['time'], React.Component){
   render(){
      return(<A time={state.time}) />
   }
}
```

**Comment by AMINDRH91** [comment]
Thank you very much for the library you developed @uxitten 
I'm waiting for your good update



My question is, what is the `performance` of this library in the big project?

**Comment by uxitten** [comment]
I didn’t see any latency in huge project.
Because we removed extra node in react tree. If you see my article about this in virgool, I explained about this

**Comment by AMINDRH91** [comment]
Yes I SEE IT,
GOOD LUCK
THANK YOU VERY MUCH
